name: fake_gps
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'




dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  geocoding: ^3.0.0
  geolocator: ^7.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


